package com.agora.enums.trading;

public enum ExecutionEventType {
    BREAKEVEN_ELIGIBLE,
    TRAILING_ELIGIBLE,
    OCO_MISSING,
    OCO_RISK_REDUCTION_PREVIEW,
    POSITION_TIMEOUT,
    GRID_SELL_FAILED_STALE,
    GRID_OUT_OF_RANGE,
    GRID_REBALANCE_LIMIT,
    REPEATED_BUY_PRESSURE,
    MARKET_RISK_FLIP,
    NEW_ENTRY_BLOCKED,
    EXECUTION_MANAGER_PROMOTION
}
