#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-/home/ubuntu/agora-trading-api}"
ENV_FILE="${ENV_FILE:-/home/ubuntu/.env.trading.secrets}"
OUTPUT_DIR="${OUTPUT_DIR:-$APP_DIR/target/schema-baseline}"
EXTRA_TABLES_FILE="${EXTRA_TABLES_FILE:-$OUTPUT_DIR/extra-in-db.txt}"
EXPECTED_TRADING_DATABASE="${EXPECTED_TRADING_DATABASE:-agora_trading}"

fail() {
  echo "[schema-cleanup-plan] FAIL: $*" >&2
  exit 1
}

ok() {
  echo "[schema-cleanup-plan] OK: $*"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"
}

read_env_key() {
  local key="$1"
  local line
  [ -f "$ENV_FILE" ] || fail "env file missing: $ENV_FILE"
  line="$(grep -E "^[[:space:]]*${key}=" "$ENV_FILE" | tail -n 1 || true)"
  if [ -z "$line" ] || ! printf '%s\n' "$line" | grep -Eq "^[[:space:]]*${key}=[^[:space:]#]"; then
    fail "missing or empty $key in $ENV_FILE"
  fi
  printf '%s\n' "${line#*=}"
}

require_cmd awk
require_cmd date
require_cmd grep
require_cmd mkdir
require_cmd mv
require_cmd mysql
require_cmd rm
require_cmd tail
require_cmd tr
require_cmd wc

[ -d "$APP_DIR" ] || fail "app dir missing: $APP_DIR"
[ -f "$EXTRA_TABLES_FILE" ] || fail "extra table list missing: $EXTRA_TABLES_FILE; run RUN_SCHEMA_BASELINE_COMPARE=1 bash scripts/verify_server.sh first"

SPRING_DATASOURCE_URL="$(read_env_key SPRING_DATASOURCE_URL)"
SPRING_DATASOURCE_USERNAME="$(read_env_key SPRING_DATASOURCE_USERNAME)"
SPRING_DATASOURCE_PASSWORD="$(read_env_key SPRING_DATASOURCE_PASSWORD)"

case "$SPRING_DATASOURCE_URL" in
  jdbc:mysql://*) ;;
  *) fail "SPRING_DATASOURCE_URL must be a jdbc:mysql URL" ;;
esac

jdbc_without_prefix="${SPRING_DATASOURCE_URL#jdbc:mysql://}"
jdbc_without_query="${jdbc_without_prefix%%\?*}"
host_port="${jdbc_without_query%%/*}"
database="${jdbc_without_query#*/}"

[ -n "$database" ] && [ "$database" != "$jdbc_without_query" ] || fail "database name missing in SPRING_DATASOURCE_URL"
if [ "$database" != "$EXPECTED_TRADING_DATABASE" ]; then
  fail "SPRING_DATASOURCE_URL must point at standalone trading database: $EXPECTED_TRADING_DATABASE"
fi
ok "SPRING_DATASOURCE_URL points at standalone trading database: $EXPECTED_TRADING_DATABASE"

if printf '%s\n' "$host_port" | grep -q ':'; then
  host="${host_port%%:*}"
  port="${host_port##*:}"
else
  host="$host_port"
  port="3306"
fi

[ -n "$host" ] || fail "database host missing in SPRING_DATASOURCE_URL"
case "$port" in
  ''|*[!0-9]*) fail "database port is invalid in SPRING_DATASOURCE_URL: $port" ;;
esac

mkdir -p "$OUTPUT_DIR"

counts_file="$OUTPUT_DIR/extra-table-row-counts.tsv"
plan_file="$OUTPUT_DIR/extra-table-cleanup-plan.sql"
tmp_counts="$counts_file.tmp"
tmp_plan="$plan_file.tmp"
generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

extra_count="$(awk 'NF { count++ } END { print count + 0 }' "$EXTRA_TABLES_FILE")"
if [ "$extra_count" = "0" ]; then
  ok "no extra tables listed in $EXTRA_TABLES_FILE"
  : > "$counts_file"
  : > "$plan_file"
  exit 0
fi

printf 'table\trow_count\n' > "$tmp_counts"
{
  echo "-- Generated by scripts/schema_extra_tables_cleanup_plan_server.sh at $generated_at"
  echo "-- Review-only cleanup plan for empty extra tables in database \`$database\`."
  echo "-- This script is NOT executed by the generator."
  echo "-- Take a MySQL backup and re-run RUN_SCHEMA_BASELINE_COMPARE=1 before applying any DROP."
  echo "-- Keep flyway_schema_history unless the Flyway baseline strategy explicitly says otherwise."
  echo ""
} > "$tmp_plan"

non_empty=0
while IFS= read -r table || [ -n "$table" ]; do
  table="$(printf '%s' "$table" | tr -d '[:space:]')"
  [ -n "$table" ] || continue
  case "$table" in
    *[!A-Za-z0-9_]*)
      fail "unsafe table name in $EXTRA_TABLES_FILE: $table"
      ;;
  esac

  row_count="$(MYSQL_PWD="$SPRING_DATASOURCE_PASSWORD" mysql \
    --batch \
    --skip-column-names \
    -h "$host" \
    -P "$port" \
    -u "$SPRING_DATASOURCE_USERNAME" \
    "$database" \
    -e "SELECT COUNT(*) FROM \`$table\`;")"
  case "$row_count" in
    ''|*[!0-9]*) fail "invalid row count for $table: $row_count" ;;
  esac
  printf '%s\t%s\n' "$table" "$row_count" >> "$tmp_counts"
  if [ "$row_count" != "0" ]; then
    non_empty=$((non_empty + 1))
  fi

  {
    echo "-- $table row_count=$row_count"
    if [ "$row_count" = "0" ]; then
      echo "-- DROP TABLE \`$table\`;"
    else
      echo "-- NOT EMPTY: do not drop \`$table\`."
    fi
    echo ""
  } >> "$tmp_plan"
done < "$EXTRA_TABLES_FILE"

mv "$tmp_counts" "$counts_file"
mv "$tmp_plan" "$plan_file"
rm -f "$tmp_counts"

echo "[schema-cleanup-plan] extra table row counts -> $counts_file"
echo "[schema-cleanup-plan] review-only cleanup plan -> $plan_file"

if [ "$non_empty" != "0" ]; then
  fail "$non_empty extra table(s) are not empty; inspect $counts_file before planning cleanup"
fi

ok "all listed extra tables are empty; review $plan_file before any manual cleanup"
