-- Forward-only Trading evidence schema. This migration only creates new tables.
-- No collector, provider ingestion, scheduler, or trading execution is enabled here.

CREATE TABLE `executable_quote_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dedupe_key` char(64) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `symbol` varchar(30) NOT NULL,
  `instrument_type` varchar(16) NOT NULL,
  `snapshot_kind` varchar(16) NOT NULL,
  `event_at` datetime(6) NOT NULL,
  `provider_at` datetime(6) NOT NULL,
  `received_at` datetime(6) NOT NULL,
  `ingested_at` datetime(6) NOT NULL,
  `best_bid_price` decimal(30,12) NOT NULL,
  `best_bid_size` decimal(30,12) NOT NULL,
  `best_ask_price` decimal(30,12) NOT NULL,
  `best_ask_size` decimal(30,12) NOT NULL,
  `depth_json` json DEFAULT NULL,
  `provider_sequence` varchar(128) DEFAULT NULL,
  `source_mode` varchar(24) NOT NULL,
  `raw_payload_sha256` char(64) NOT NULL,
  `provider_cursor` varchar(255) DEFAULT NULL,
  `provider_page_key` varchar(128) DEFAULT NULL,
  `gap_manifest_id` char(64) DEFAULT NULL,
  `gap_dataset` varchar(64) DEFAULT NULL,
  `gap_range_start` datetime(6) DEFAULT NULL,
  `gap_range_end` datetime(6) DEFAULT NULL,
  `retention_class` varchar(32) NOT NULL DEFAULT 'TRADING_EVIDENCE_LONG',
  `retain_until` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_executable_quote_snapshot_dedupe` (`dedupe_key`),
  KEY `idx_executable_quote_symbol_provider_event` (`symbol`,`provider`,`event_at`),
  KEY `idx_executable_quote_gap` (`gap_manifest_id`,`gap_range_start`),
  CONSTRAINT `chk_executable_quote_dedupe_hash` CHECK (`dedupe_key` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_executable_quote_raw_hash` CHECK (`raw_payload_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_executable_quote_source_mode` CHECK (`source_mode` IN ('FORWARD','HISTORICAL_BACKFILL')),
  CONSTRAINT `chk_executable_quote_snapshot_kind` CHECK (`snapshot_kind` IN ('QUOTE','DEPTH')),
  CONSTRAINT `chk_executable_quote_instrument` CHECK (`instrument_type` IN ('SPOT','SWAP','FUTURES')),
  CONSTRAINT `chk_executable_quote_top` CHECK (`best_bid_price` > 0 AND `best_ask_price` > 0 AND `best_bid_price` <= `best_ask_price` AND `best_bid_size` >= 0 AND `best_ask_size` >= 0),
  CONSTRAINT `chk_executable_quote_ingest_order` CHECK (`ingested_at` >= `received_at`),
  CONSTRAINT `chk_executable_quote_gap_link` CHECK ((`gap_manifest_id` IS NULL AND `gap_dataset` IS NULL AND `gap_range_start` IS NULL AND `gap_range_end` IS NULL) OR (`gap_manifest_id` IS NOT NULL AND `gap_dataset` IS NOT NULL AND `gap_range_start` IS NOT NULL AND `gap_range_end` IS NOT NULL AND `gap_range_start` < `gap_range_end`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only executable top-of-book/depth evidence; hourly scalar indicators are forbidden';

CREATE TABLE `fill_fee_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dedupe_key` char(64) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `account_ref_hash` char(64) NOT NULL,
  `symbol` varchar(30) NOT NULL,
  `instrument_type` varchar(16) NOT NULL,
  `order_id` varchar(128) NOT NULL,
  `trade_id` varchar(128) NOT NULL,
  `event_at` datetime(6) NOT NULL,
  `provider_at` datetime(6) NOT NULL,
  `received_at` datetime(6) NOT NULL,
  `ingested_at` datetime(6) NOT NULL,
  `signed_fee_amount` decimal(30,12) NOT NULL,
  `fee_currency` varchar(20) NOT NULL,
  `fee_sign_semantic` varchar(64) NOT NULL,
  `source_mode` varchar(24) NOT NULL,
  `raw_payload_sha256` char(64) NOT NULL,
  `provider_cursor` varchar(255) DEFAULT NULL,
  `provider_page_key` varchar(128) DEFAULT NULL,
  `gap_manifest_id` char(64) DEFAULT NULL,
  `gap_dataset` varchar(64) DEFAULT NULL,
  `gap_range_start` datetime(6) DEFAULT NULL,
  `gap_range_end` datetime(6) DEFAULT NULL,
  `retention_class` varchar(32) NOT NULL DEFAULT 'TRADING_EVIDENCE_LONG',
  `retain_until` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fill_fee_ledger_dedupe` (`dedupe_key`),
  UNIQUE KEY `uk_fill_fee_provider_trade_currency` (`provider`,`account_ref_hash`,`trade_id`,`fee_currency`),
  KEY `idx_fill_fee_symbol_event` (`symbol`,`event_at`),
  KEY `idx_fill_fee_gap` (`gap_manifest_id`,`gap_range_start`),
  CONSTRAINT `chk_fill_fee_dedupe_hash` CHECK (`dedupe_key` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_fill_fee_account_hash` CHECK (`account_ref_hash` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_fill_fee_raw_hash` CHECK (`raw_payload_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_fill_fee_source_mode` CHECK (`source_mode` IN ('FORWARD','HISTORICAL_BACKFILL')),
  CONSTRAINT `chk_fill_fee_semantic` CHECK (`fee_sign_semantic` = 'COST_NEGATIVE_REBATE_POSITIVE'),
  CONSTRAINT `chk_fill_fee_ingest_order` CHECK (`ingested_at` >= `received_at`),
  CONSTRAINT `chk_fill_fee_gap_link` CHECK ((`gap_manifest_id` IS NULL AND `gap_dataset` IS NULL AND `gap_range_start` IS NULL AND `gap_range_end` IS NULL) OR (`gap_manifest_id` IS NOT NULL AND `gap_dataset` IS NOT NULL AND `gap_range_start` IS NOT NULL AND `gap_range_end` IS NOT NULL AND `gap_range_start` < `gap_range_end`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only signed fill fee facts; costs are negative and rebates positive';

CREATE TABLE `funding_bill_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dedupe_key` char(64) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `account_ref_hash` char(64) NOT NULL,
  `symbol` varchar(30) NOT NULL,
  `instrument_type` varchar(16) NOT NULL,
  `bill_id` varchar(128) NOT NULL,
  `position_ref` varchar(128) DEFAULT NULL,
  `event_at` datetime(6) NOT NULL,
  `provider_at` datetime(6) NOT NULL,
  `received_at` datetime(6) NOT NULL,
  `ingested_at` datetime(6) NOT NULL,
  `signed_funding_amount` decimal(30,12) NOT NULL,
  `funding_currency` varchar(20) NOT NULL,
  `funding_sign_semantic` varchar(64) NOT NULL,
  `source_mode` varchar(24) NOT NULL,
  `raw_payload_sha256` char(64) NOT NULL,
  `provider_cursor` varchar(255) DEFAULT NULL,
  `provider_page_key` varchar(128) DEFAULT NULL,
  `gap_manifest_id` char(64) DEFAULT NULL,
  `gap_dataset` varchar(64) DEFAULT NULL,
  `gap_range_start` datetime(6) DEFAULT NULL,
  `gap_range_end` datetime(6) DEFAULT NULL,
  `retention_class` varchar(32) NOT NULL DEFAULT 'TRADING_EVIDENCE_LONG',
  `retain_until` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_funding_bill_ledger_dedupe` (`dedupe_key`),
  UNIQUE KEY `uk_funding_bill_provider_account_bill` (`provider`,`account_ref_hash`,`bill_id`),
  KEY `idx_funding_bill_symbol_event` (`symbol`,`event_at`),
  KEY `idx_funding_bill_gap` (`gap_manifest_id`,`gap_range_start`),
  CONSTRAINT `chk_funding_bill_dedupe_hash` CHECK (`dedupe_key` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_funding_bill_account_hash` CHECK (`account_ref_hash` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_funding_bill_raw_hash` CHECK (`raw_payload_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_funding_bill_source_mode` CHECK (`source_mode` IN ('FORWARD','HISTORICAL_BACKFILL')),
  CONSTRAINT `chk_funding_bill_semantic` CHECK (`funding_sign_semantic` = 'PAID_NEGATIVE_RECEIVED_POSITIVE'),
  CONSTRAINT `chk_funding_bill_ingest_order` CHECK (`ingested_at` >= `received_at`),
  CONSTRAINT `chk_funding_bill_gap_link` CHECK ((`gap_manifest_id` IS NULL AND `gap_dataset` IS NULL AND `gap_range_start` IS NULL AND `gap_range_end` IS NULL) OR (`gap_manifest_id` IS NOT NULL AND `gap_dataset` IS NOT NULL AND `gap_range_start` IS NOT NULL AND `gap_range_end` IS NOT NULL AND `gap_range_start` < `gap_range_end`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only signed funding bills; paid is negative and received positive';

CREATE TABLE `margin_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `dedupe_key` char(64) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `account_ref_hash` char(64) NOT NULL,
  `symbol` varchar(30) DEFAULT NULL,
  `instrument_type` varchar(16) NOT NULL,
  `margin_mode` varchar(16) NOT NULL,
  `event_at` datetime(6) NOT NULL,
  `provider_at` datetime(6) NOT NULL,
  `received_at` datetime(6) NOT NULL,
  `ingested_at` datetime(6) NOT NULL,
  `equity` decimal(30,12) NOT NULL,
  `available_balance` decimal(30,12) NOT NULL,
  `used_margin` decimal(30,12) NOT NULL,
  `maintenance_margin` decimal(30,12) NOT NULL,
  `margin_ratio` decimal(30,12) DEFAULT NULL,
  `currency` varchar(20) NOT NULL,
  `source_mode` varchar(24) NOT NULL,
  `raw_payload_sha256` char(64) NOT NULL,
  `provider_cursor` varchar(255) DEFAULT NULL,
  `provider_page_key` varchar(128) DEFAULT NULL,
  `gap_manifest_id` char(64) DEFAULT NULL,
  `gap_dataset` varchar(64) DEFAULT NULL,
  `gap_range_start` datetime(6) DEFAULT NULL,
  `gap_range_end` datetime(6) DEFAULT NULL,
  `retention_class` varchar(32) NOT NULL DEFAULT 'TRADING_EVIDENCE_LONG',
  `retain_until` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_margin_snapshot_dedupe` (`dedupe_key`),
  KEY `idx_margin_snapshot_account_event` (`provider`,`account_ref_hash`,`event_at`),
  KEY `idx_margin_snapshot_symbol_event` (`symbol`,`event_at`),
  KEY `idx_margin_snapshot_gap` (`gap_manifest_id`,`gap_range_start`),
  CONSTRAINT `chk_margin_snapshot_dedupe_hash` CHECK (`dedupe_key` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_margin_snapshot_account_hash` CHECK (`account_ref_hash` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_margin_snapshot_raw_hash` CHECK (`raw_payload_sha256` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_margin_snapshot_source_mode` CHECK (`source_mode` IN ('FORWARD','HISTORICAL_BACKFILL')),
  CONSTRAINT `chk_margin_snapshot_instrument` CHECK (`instrument_type` IN ('SPOT','MARGIN','SWAP','FUTURES','PORTFOLIO')),
  CONSTRAINT `chk_margin_snapshot_mode` CHECK (`margin_mode` IN ('CASH','CROSS','ISOLATED','PORTFOLIO')),
  CONSTRAINT `chk_margin_snapshot_values` CHECK (`equity` >= 0 AND `available_balance` >= 0 AND `used_margin` >= 0 AND `maintenance_margin` >= 0 AND (`margin_ratio` IS NULL OR `margin_ratio` >= 0)),
  CONSTRAINT `chk_margin_snapshot_ingest_order` CHECK (`ingested_at` >= `received_at`),
  CONSTRAINT `chk_margin_snapshot_gap_link` CHECK ((`gap_manifest_id` IS NULL AND `gap_dataset` IS NULL AND `gap_range_start` IS NULL AND `gap_range_end` IS NULL) OR (`gap_manifest_id` IS NOT NULL AND `gap_dataset` IS NOT NULL AND `gap_range_start` IS NOT NULL AND `gap_range_end` IS NOT NULL AND `gap_range_start` < `gap_range_end`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only account margin snapshots';
