CREATE TABLE IF NOT EXISTS exact_trade_fill_collection_run (
  id bigint NOT NULL AUTO_INCREMENT,
  run_id char(64) NOT NULL,
  provider varchar(32) NOT NULL,
  account_ref_hash char(64) NOT NULL,
  instrument_id varchar(64) NOT NULL,
  instrument_type varchar(32) NOT NULL,
  binding_scope_sha256 char(64) NOT NULL,
  status varchar(32) NOT NULL,
  started_at timestamp(6) NOT NULL,
  completed_at timestamp(6) NOT NULL,
  page_count int NOT NULL,
  fill_count int NOT NULL,
  terminal_cursor varchar(255) DEFAULT NULL,
  canonical_fill_set_sha256 char(64) NOT NULL,
  prior_stable_run_id char(64) DEFAULT NULL,
  created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_exact_fill_run_id (run_id),
  KEY ix_exact_fill_run_scope (provider, account_ref_hash, instrument_id, instrument_type, binding_scope_sha256, completed_at),
  CONSTRAINT chk_exact_fill_run_status CHECK (status IN ('COMPLETE_CANDIDATE','COMPLETE_STABLE')),
  CONSTRAINT chk_exact_fill_run_hash CHECK (canonical_fill_set_sha256 REGEXP '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS exact_trade_fill_page_manifest (
  id bigint NOT NULL AUTO_INCREMENT,
  run_id char(64) NOT NULL,
  page_index int NOT NULL,
  request_cursor varchar(255) DEFAULT NULL,
  next_cursor varchar(255) DEFAULT NULL,
  page_key char(64) NOT NULL,
  page_sha256 char(64) NOT NULL,
  fill_count int NOT NULL,
  terminal_page boolean NOT NULL,
  collected_at timestamp(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_exact_fill_page_index (run_id, page_index),
  UNIQUE KEY uk_exact_fill_page_key (run_id, page_key),
  CONSTRAINT chk_exact_fill_page_hash CHECK (page_sha256 REGEXP '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS immutable_trade_fill (
  id bigint NOT NULL AUTO_INCREMENT,
  fill_identity_sha256 char(64) NOT NULL,
  immutable_content_sha256 char(64) NOT NULL,
  provider varchar(32) NOT NULL,
  account_ref_hash char(64) NOT NULL,
  instrument_id varchar(64) NOT NULL,
  instrument_type varchar(32) NOT NULL,
  order_id varchar(128) NOT NULL,
  trade_id varchar(128) NOT NULL,
  bill_id varchar(128) NOT NULL,
  fill_at timestamp(6) NOT NULL,
  side varchar(8) NOT NULL,
  fill_price decimal(30,12) NOT NULL,
  fill_quantity decimal(30,12) NOT NULL,
  signed_fee_amount decimal(30,12) NOT NULL,
  fee_currency varchar(32) NOT NULL,
  liquidity_role varchar(32) DEFAULT NULL,
  source_run_id char(64) NOT NULL,
  source_page_key char(64) NOT NULL,
  collected_at timestamp(6) NOT NULL,
  raw_payload_sha256 char(64) NOT NULL,
  cohort_id varchar(128) DEFAULT NULL,
  runtime_decision_id bigint DEFAULT NULL,
  live_signal_id bigint DEFAULT NULL,
  intended_child_order_id varchar(128) DEFAULT NULL,
  actual_child_order_id varchar(128) DEFAULT NULL,
  created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_immutable_trade_fill_identity (provider, account_ref_hash, order_id, trade_id),
  UNIQUE KEY uk_immutable_trade_fill_identity_hash (fill_identity_sha256),
  KEY ix_immutable_trade_fill_run (source_run_id),
  KEY ix_immutable_trade_fill_episode (cohort_id, runtime_decision_id, live_signal_id),
  CONSTRAINT chk_immutable_trade_fill_side CHECK (side IN ('BUY','SELL')),
  CONSTRAINT chk_immutable_trade_fill_identity_hash CHECK (fill_identity_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_immutable_trade_fill_content_hash CHECK (immutable_content_sha256 REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT chk_immutable_trade_fill_raw_hash CHECK (raw_payload_sha256 REGEXP '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS exact_trade_fill_run_item (
  run_id char(64) NOT NULL,
  fill_identity_sha256 char(64) NOT NULL,
  page_key char(64) NOT NULL,
  PRIMARY KEY (run_id, fill_identity_sha256),
  KEY ix_exact_fill_run_item_fill (fill_identity_sha256)
);
